### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by ghost** [oconnor663/fbmessenger#63]
The installation failed.
```
$>./run.sh
Traceback (most recent call last):
  File "./bin/fbmessenger", line 3, in <module>
    from fbmessenger import main
  File "/home/tom/git/fbmessenger/fbmessenger/main.py", line 4, in <module>
    from . import application
  File "/home/tom/git/fbmessenger/fbmessenger/application.py", line 4, in <module>
    import sip
ImportError: No module named 'sip'
$>
```

**Comment by oconnor663** [comment]
You're probably missing the PyQt4 dependency?

That said, unfortunately, this app hasn't been working for years. The facebook.com endpoints that it used to talk to are gone. So even if you get it to open the main window, it won't be able to load any UI.
